services:
  - type: web
    name: reloadbr-backend
    env: python
    plan: free
    buildCommand: pip install -r backend/requirements.txt
    startCommand: python app.py
    workingDirectory: backend
