services:
  - type: web
    name: reloadbr-backend
    env: python
    region: oregon
    buildCommand: pip install -r backend/requirements.txt
    startCommand: python backend/app.py
    plan: free
    autoDeploy: true
